### ISSUE TITLE
Error "400: Bad Request" on all queries

### ISSUE THREAD

**Issue by maia** [hassio-addons/addon-sqlite-web#281] opened 2023-10-20 15:11 UTC
I'm failing to run any queries from the SQLite Web interface, everything returns "400: Bad Request", e.g. the queries listed [here](https://community.home-assistant.io/t/how-to-keep-your-recorder-database-size-under-control/295795/126) such as:
```sql
SELECT
  COUNT(*) AS cnt,
  COUNT(*) * 100 / (SELECT COUNT(*) FROM states) AS cnt_pct,
  states_meta.entity_id
FROM states
INNER JOIN states_meta ON states.metadata_id=states_meta.metadata_id
GROUP BY states_meta.entity_id
ORDER BY cnt DESC
``` 
The addon itself seems to be configured properly, there's nothing in the addon log that looks like an error to me and the web console shows it found /config/home-assistant_v2.db with 13 tables, 20 indexes and 2GB size. 

But the HA Core logs show:
```
Logger: homeassistant.components.http.security_filter
Source: components/http/security_filter.py:66
Integration: HTTP (documentation, issues)
First occurred: 10:02:23 (3 occurrences)
Last logged: 10:04:34

Filtered a request with unsafe byte query string: /query/?sql=SELECT%0D%0A++COUNT%28*%29+AS+cnt%2C%0D%0A++COUNT%28*%29+*+100+%2F+%28SELECT+COUNT%28*%29+FROM+states%29+AS+cnt_pct%2C%0D%0A++states_meta.entity_id%0D%0AFROM+states%0D%0AINNER+JOIN+states_meta+ON+states.metadata_id%3Dstates_meta.metadata_id%0D%0AGROUP+BY+states_meta.entity_id%0D%0AORDER+BY+cnt+DESC
```

Log:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: SQLite Web
 Explore your SQLite database
-----------------------------------------------------------
 Add-on version: 3.10.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.0  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.10.3
 Home Assistant Supervisor: 2023.10.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-sqlite-web: starting
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-sqlite-web successfully started
s6-rc: info: service sqlite-web: starting
s6-rc: info: service sqlite-web successfully started
s6-rc: info: service init-nginx successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
[09:50:48] INFO: Starting SQLite Web...
s6-rc: info: service legacy-services successfully started
 * Serving Flask app 'sqlite_web.sqlite_web'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8080
Press CTRL+C to quit
[09:50:50] INFO: Starting NGINX...
127.0.0.1 - - [19/Oct/2023 09:50:54] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 09:51:00] "GET /event_data/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 09:51:22] "GET /states/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 09:51:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 09:51:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 09:52:02] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 09:52:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 09:52:37] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 09:52:47] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 09:54:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 09:54:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 09:59:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 09:59:36] "GET /states/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 09:59:37] "GET /event_data/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 09:59:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 10:02:19] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 10:02:33] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 10:04:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2023 10:05:00] "GET / HTTP/1.1" 200 -
```

Thanks!

**Comment by ElPunto** [comment] 2023-10-20 18:00
My queries all failed too. When I removed the Line Feeds and made it a single line statement the queries and updates worked again.

**Comment by maia** [comment] 2023-10-22 15:09
@BigThunderSR Good to know, might help some people. Unfortunately I don't have any old versions in my backups I could restore, as 3.10.0 was my first install of the addon.

**Comment by smaknomercy** [comment] 2023-10-22 16:48
Same problem

**Comment by DanHaed** [comment] 2023-10-24 09:46
@BigThunderSR Thank you for your service. Your Backup worked for me.

@maia restoring from Backup is pretty easy. First delete the installed Addon then go to Settings > System > Backup and choose Upload Backup in the top right menu and upload the tar.

**Comment by HansRemmerswaal** [comment] 2023-10-25 05:37
It also worked for me. But don't forget to disable the "Auto update" as today I suddenly had 3.10.0 again...

**Comment by jphoke** [comment] 2023-10-26 15:52
> My queries all failed too. When I removed the Line Feeds and made it a single line statement the queries and updates worked again.

When I try that I get 404: Not Found error

**Comment by BradleyCampbell** [comment] 2023-10-27 10:27
I am also receiving this error for 99% of queries.  Running v3.10.0 of the add-on.  Unfortunately no back to restore a previous version from

**Comment by BradleyCampbell** [comment] 2023-10-27 20:59
> > I am also receiving this error for 99% of queries.  Running v3.10.0 of the add-on.  Unfortunately no back to restore a previous version from.
> > Is there any eta on a fix?
> 
> You can use the backup file I provided here until a fix is available: [#281 (comment)](https://github.com/hassio-addons/addon-sqlite-web/issues/281#issuecomment-1774148189)

Thank you very much!  Works perfectly.  Turned auto update off for the time being.

**Comment by wernerhp** [comment] 2023-10-28 23:47
![Screenshot 2023-10-29 at 01 46 57](https://github.com/hassio-addons/addon-sqlite-web/assets/2578772/ef171b2e-bfca-4468-ae23-59b2a61632ce)

![Screenshot 2023-10-29 at 01 47 21](https://github.com/hassio-addons/addon-sqlite-web/assets/2578772/ef486e2f-528d-404d-ad0f-2baa680a28f9)

**Comment by Linwood-F** [comment] 2023-11-01 16:59
> It seems that the queries have to be all on one line, then they work

Doesn't work for me, still get the 400.

**Comment by sofa74surfer** [comment] 2023-11-02 05:43
One line statement doesn't work for me - I get a Bad Request too. Perhaps my statement is too long, because it automatically wraps line.
`select cast(round((max(s.state) - min(s.state)),0) as int) as state FROM statistics_meta sm inner join statistics s on s.metadata_id = sm.id where sm.statistic_id = 'sensor.heatpump_19_hz_power_consumption' and s.created_ts > (strftime('%s', 'now') - (1*60*60*24));`
I reverted to 3.9.2, that works.

**Comment by wigster** [comment] 2023-11-02 08:41
There seem to be two things. If I make a query like:
```
SELECT * FROM "statistics" where metadata_id=154;
```
This works if (a) it's on one line. (b) I actually click on the statistics database and then query, as opposed to typing it into the main query box. If I don't do (b), I get the 404 error. If I do (b) but not (a), I get a 400 error. I've managed to get some pretty long queries done in this way, but they are completely unreadable.

In any case, this is at best a bad workaround and clearly there is some sort of bug.

**Comment by Nico96R** [comment] 2023-11-05 11:38
@wigster I could also fix my queries by writing them in one line. Using the Query box at the home screen also gives me the error 404.
Running Version 3.10.0

**Comment by bcutter** [comment] 2023-11-06 14:11
I discovered that multi-line statements create the `400: Bad Request` web page and create an HA log entry
```
Logger: homeassistant.components.http.security_filter
Source: components/http/security_filter.py:66
Integration: HTTP (documentation, issues)
First occurred: 14:43:21 (11 occurrences)
Last logged: 15:04:32

Filtered a request with unsafe byte query string: /api/hassio_ingress/OcV5DOvdW6LHTNdqBIfJ1Uv8c_7uheSy7g5Jay6murI/states/query/?ordering=&export_ordering=&sql=SELECT+*+FROM+%22states%22+WHERE+metadata_id%3D%28SELECT+metadata_id+FROM+states_meta+WHERE+entity_id%3D%22sensor.statistics_entities_automations_disabled%22%29%0D%0AORDER+BY+created+DESC%3B
```

Using one-line statements instead works again. What an ugly bug... no matter when or why this has been introduced. Either HA Core (starting 2023.4 likely) or one of the latest addon updates.

Home screen query box not working at all, no matter if multi- or one-line statements are used. I tend to say the addon is partly broken.

**Comment by bcutter** [comment] 2023-11-06 14:45
> @bcutter You need to revert back to v3.9.2, a few replies back is described how to do this.

Strongly disagree. That's a workaround (like using one-liner statements), at best. A **_solution_** would be the addon to provide a new version which downgrades it to a working state version.

**Comment by Linwood-F** [comment] 2023-11-06 15:30
> > @bcutter You need to revert back to v3.9.2, a few replies back is described how to do this.
> 
> Strongly disagree. That's a workaround (like using one-liner statements), at best. A **_solution_** would be the addon to provide a new version which downgrades it to a working state version.

I think it was offered as a workaround to someone, not a final solution.  I assume the author will at some point tackle this and fix it more completely.  They may be off on a long ocean cruise or something.  :)

**Comment by HansRemmerswaal** [comment] 2023-11-06 16:46
Indeed it's currently the only working solution till the author is coming with a fix on 3.10.0
And to be honest, there is nothing wrong with 3.9.2.

So let the author enjoy that "long ocean cruise" and who knows it gets resolves somewhere in the future.

**Comment by bcutter** [comment] 2023-11-07 10:54
OK another classic sit and wait situation. Luckily I don't use the addon to query stuff on a daily basis so my workaround of using one-lined statements is my way to go for now.

Clearly it must be one of these changes which has introduced these issues:

![image](https://github.com/hassio-addons/addon-sqlite-web/assets/13799156/69fa9bf0-ad3e-4e2e-b53f-b7774b0f15be)

Looking forward to a new release fixing these.

**Comment by matthewhadley** [comment] 2023-11-15 17:28
Note the recent `version 4.0.0` of this Add-On does **not** fix this issue.

**Comment by Linwood-F** [comment] 2023-11-15 17:39
That's a shame.   It does appear that with current HA versions the old working one still works (I am a bit confused by the whole /config -> /homeassistant migration whether it would break anything, but the link from config still seems to work with older tools).

**Comment by thanasiskalos** [comment] 2023-11-16 11:33
> Note the recent `version 4.0.0` of this Add-On does **not** fix this issue.

agree. I can understand the effort the developers put on , but a know bug exists for more than a month , new release is published and the bug still exists.

**Comment by Linwood-F** [comment] 2023-11-16 14:04
> agree. I can understand the effort the developers put on , but a known bug exists for more than a month , new release is published and the bug still exists.

Just from looking at the PR history the "owner" of this is someone who seems to own about half the addons out there, and the most recent changes were largely compatibility changes for ongoing HA work done by someone else.  I.e. I think this addon is a tail wagged by a larger dog for the latest changes, not someone actually working on this add-on specifically.

I don't know any of the folks involved nor am I involved in HA generally, just remember these are all volunteers who keep this particular train running, so when it runs on time, be impressed, and a little forgiving if it's late.

**Comment by HansRemmerswaal** [comment] 2023-11-16 19:10
> > agree. I can understand the effort the developers put on , but a known bug exists for more than a month , new release is published and the bug still exists.
> 
> Just from looking at the PR history the "owner" of this is someone who seems to own about half the addons out there, and the most recent changes were largely compatibility changes for ongoing HA work done by someone else. I.e. I think this addon is a tail wagged by a larger dog for the latest changes, not someone actually working on this add-on specifically.
> 
> I don't know any of the folks involved nor am I involved in HA generally, just remember these are all volunteers who keep this particular train running, so when it runs on time, be impressed, and a little forgiving if it's late.


I fully agree with you. I did a rollback to 3.9.2 and all is working fine for me. So even if it takes a year to fix the issue, I'm not blocked.

But I have to say that I was surprised to see that after 3.10.0 also 4.0.0 is having the issue. I assume that the person who released the latest version did some basic testing before releasing it, and for that person it then worked. So is there maybe something "else" causing the issue? A conflict with our configuration maybe?

**Comment by Santanachia** [comment] 2023-11-23 12:04
A question for those who have withdrawn the version to 3.9.2:
are your queries sent using the `GET` method (the entire query appears in the address bar)?

**Comment by Santanachia** [comment] 2023-11-23 12:07
@frenck could you take a look at this problem (or write who owns the project and should look at it)?

**Comment by HansRemmerswaal** [comment] 2023-11-24 07:24
> A question for those who have withdrawn the version to 3.9.2: are your queries sent using the `GET` method (the entire query appears in the address bar)?

Not sure if I fully understand your question. I upgrade now to 4.0.0.

In the address bar I see http://84.86.145.83:8123/a0d7b954_sqlite-web/ingress
And I run the query select * from events

![Annotation 2023-11-24 082110](https://github.com/hassio-addons/addon-sqlite-web/assets/116959990/2b5cc934-d69b-4519-82e8-274fed8171de)

![Annotation 2023-11-24 082110](https://github.com/hassio-addons/addon-sqlite-web/assets/116959990/267c95c7-90a7-49a9-b58e-985c6f3dd12a)

Top right we have the button Query, so I click on it and try the same.

In the address bar I see http://84.86.145.83:8123/a0d7b954_sqlite-web/ingress
And I run the query select * from events

![Annotation 2023-11-24 082110](https://github.com/hassio-addons/addon-sqlite-web/assets/116959990/dd7ffdc3-5c63-4623-8580-9749e769b2a0)

In the address bar I see http://84.86.145.83:8123/a0d7b954_sqlite-web/ingress
And I run the query in 2 lines
select * 
 from events

![Annotation 2023-11-24 082110](https://github.com/hassio-addons/addon-sqlite-web/assets/116959990/52ee52cb-1635-4b12-946a-9d6d30a51935)
![Annotation 2023-11-24 082110](https://github.com/hassio-addons/addon-sqlite-web/assets/116959990/ce2e08de-d938-477d-857d-8307cf5da037)

**Comment by HansRemmerswaal** [comment] 2023-11-24 07:39
> A question for those who have withdrawn the version to 3.9.2: are your queries sent using the `GET` method (the entire query appears in the address bar)?

Not sure if I fully understand the question, but I upgrade now to 4.0.0.
In the address bar I see http://84.86.145.83:8123/a0d7b954_sqlite-web/ingress

1) I run the query in the bottom part and it fails
select * from events 

![1](https://github.com/hassio-addons/addon-sqlite-web/assets/116959990/c029113d-b29a-42f1-82b4-7dbea221c8d1)
![2](https://github.com/hassio-addons/addon-sqlite-web/assets/116959990/83c4cf4f-e448-4f76-8513-a2d42af62115)

2) I click on top right "Query" and enter the query in the top part and it's working
select * from events 

![3](https://github.com/hassio-addons/addon-sqlite-web/assets/116959990/3ef302e5-e024-4881-bada-8d38a821acc9)

3) I click on top right "Query" and enter the query **across 2 lines** in the top part and it's failing
select * 
from events 

![4](https://github.com/hassio-addons/addon-sqlite-web/assets/116959990/5c9dc994-5771-48b8-9248-620202fc03fb)
![5](https://github.com/hassio-addons/addon-sqlite-web/assets/116959990/9f90fed1-76b3-4f4d-ad16-2009bbe563e9)

**Comment by HansRemmerswaal** [comment] 2023-12-24 08:34
The issue is still there, so keep the issue open.

**Comment by huizebruin** [comment] 2023-12-27 12:42
Here also the same problem.

**Comment by huizebruin** [comment] 2023-12-27 13:20
> > A question for those who have withdrawn the version to 3.9.2: are your queries sent using the `GET` method (the entire query appears in the address bar)?
> 
> Not sure if I fully understand the question, but I upgrade now to 4.0.0. In the address bar I see http://84.86.145.83:8123/a0d7b954_sqlite-web/ingress
> 
> 1. I run the query in the bottom part and it fails
>    select * from events
> 
> ![1](https://private-user-images.githubusercontent.com/116959990/285389453-c029113d-b29a-42f1-82b4-7dbea221c8d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2ODMzNTYsIm5iZiI6MTcwMzY4MzA1NiwicGF0aCI6Ii8xMTY5NTk5OTAvMjg1Mzg5NDUzLWMwMjkxMTNkLWIyOWEtNDJmMS04MmI0LTdkYmVhMjIxYzhkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QxMzE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDljM2U3ZTI0NGQ1MDkyYzM4ODYyNzM1YTE1NTQ0MGUyMzI0MWZkYTM4NGQ5MjgzNDcxNGI0NjVjNjczODI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gSatIbj2UscLU_Z37PzdomyjND5ZZAn4KXtBJ-kMg-c) ![2](https://private-user-images.githubusercontent.com/116959990/285389604-83c4cf4f-e448-4f76-8513-a2d42af62115.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2ODMzNTYsIm5iZiI6MTcwMzY4MzA1NiwicGF0aCI6Ii8xMTY5NTk5OTAvMjg1Mzg5NjA0LTgzYzRjZjRmLWU0NDgtNGY3Ni04NTEzLWEyZDQyYWY2MjExNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QxMzE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjdiYmRiYTg2M2NkZmQ0MWYwYmIyN2NlMzcxYmJmYmU5OTRhMzJhODMzYzlhMjFlMjJiNDUwNGRjZDRiYTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VXLYm_lYQlmFjCsIHNU0bgL04Zvo8dhhLncTcj1ikYM)
> 
> 2. I click on top right "Query" and enter the query in the top part and it's working
>    select * from events
> 
> ![3](https://private-user-images.githubusercontent.com/116959990/285389928-3ef302e5-e024-4881-bada-8d38a821acc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2ODMzNTYsIm5iZiI6MTcwMzY4MzA1NiwicGF0aCI6Ii8xMTY5NTk5OTAvMjg1Mzg5OTI4LTNlZjMwMmU1LWUwMjQtNDg4MS1iYWRhLThkMzhhODIxYWNjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QxMzE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTkxNzg4MWUyYWM5ZjM2ZjY4OTVkNjY4ZDBiOGQ0YThkNGU0ZDVhMzE1ZWRjYTc4MzNlOTU5NWZhM2E3ZjRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X5nPnDwsUvjUQbqhOqiMUTt6SJ9Jx4mzDPttqGiJqas)
> 
> 3. I click on top right "Query" and enter the query **across 2 lines** in the top part and it's failing
>    select *
>    from events
> 
> ![4](https://private-user-images.githubusercontent.com/116959990/285390036-5c9dc994-5771-48b8-9248-620202fc03fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2ODMzNTYsIm5iZiI6MTcwMzY4MzA1NiwicGF0aCI6Ii8xMTY5NTk5OTAvMjg1MzkwMDM2LTVjOWRjOTk0LTU3NzEtNDhiOC05MjQ4LTYyMDIwMmZjMDNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QxMzE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDdjZGNjOTI3YTdhMzAwYzkyYzQ4N2NmMzk1YzBjZGJiM2NjZTE1YWU0M2ZlY2E0MjU3MDIzYmZmMzIzYzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NLNEcZuuDkdUlLe37FcGVdbP4SsXD1QkkOUSj4cvB3Y) ![5](https://private-user-images.githubusercontent.com/116959990/285390044-9f90fed1-76b3-4f4d-ad16-2009bbe563e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2ODMzNTYsIm5iZiI6MTcwMzY4MzA1NiwicGF0aCI6Ii8xMTY5NTk5OTAvMjg1MzkwMDQ0LTlmOTBmZWQxLTc2YjMtNGY0ZC1hZDE2LTIwMDliYmU1NjNlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QxMzE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWRhMjI5ZjJiMjBiOTYyYTVlOTlhNzEyZGNiMTEwNTIzODQ3N2E1M2UzZDNmYzllYWI3OTAzODhmZmM3YTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5_J4fWhGV944jPurjiqYdmc74Sm3cc6LsMr4t2pnFYY)
> 
> Going to rollback to the 3.9.2 again :)

i did also the rolback to 3.9.2 by putting the backup from https://github.com/hassio-addons/addon-sqlite-web/issues/281#issuecomment-1774148189

and everything works again.
thanks.

**Comment by nkinnan** [comment] 2023-12-29 02:21
Commenting to draw attention.  This is a rather annoying bug.

**Comment by frenck** [comment] 2024-01-07 14:12
![CleanShot 2024-01-07 at 15 10 52@2x](https://github.com/hassio-addons/addon-sqlite-web/assets/195327/7ca45a4a-e639-426f-803e-b308b0907dca)

Home Assistant blocks the request. There is not much to do about that from the add-on side of things :(

**Comment by frenck** [comment] 2024-01-07 14:14
I will check with the team if we want to lower guards on the security filters in case of add-ons/ingress.

If not, there is only one place this add-on can go (the bin 🗑️ )

../Frenck

**Comment by drewkeller** [comment] 2024-01-07 17:00
As noted earlier: https://github.com/hassio-addons/addon-sqlite-web/issues/281#issuecomment-1794911347
This is likely an oversimplification, but couldn't the newlines get stripped before submitting? Or else repackage the earlier working version?

**Comment by HansRemmerswaal** [comment] 2024-01-07 22:11
What has changed between 3.9.2 and 4.0.0?
The 3.9.2. version works fine...

**Comment by HansRemmerswaal** [comment] 2024-01-08 13:14
Version 4.1.0 still has the same issue, back to 3.9.2. again...

**Comment by jphoke** [comment] 2024-01-08 14:11
> No clue what is ingress...

Ingress is a database supported by an add-on to HA for long term storage mostly (and glances integration)

**Comment by HansRemmerswaal** [comment] 2024-01-08 14:33
> > No clue what is ingress...
> 
> Ingress is a database supported by an add-on to HA for long term storage mostly (and glances integration)

But we query the SQLite database... what is this Ingress dependency suddenly doing there after release 3.9.2...

**Comment by mikke49** [comment] 2024-01-08 14:39
Ingress is not a database. It is the addon frontend, i.e. the addon's user interface shown in Home Assistant. It has always been there.

**Comment by HansRemmerswaal** [comment] 2024-01-08 14:41
Ah yes, I see it also there in the URL in 3.9.2...

http://xxx.xxx.xxx.xxx:8123/xxxxxxx_sqlite-web/**ingress**

**Comment by BartRuSec** [comment] 2024-01-08 15:13
Why this addon cannot encode (eg. base64) query param and decode it again  like here -> https://github.com/home-assistant/core/issues/103458? This is very annoying blocker ....

**Comment by frenck** [comment] 2024-01-08 16:40
> Version 4.1.0 still has the same issue, back to 3.9.2. again...

Yes this issue is still open...

**Comment by frenck** [comment] 2024-01-08 16:41
> Why this addon cannot encode (eg. base64) query param and decode it again like here -> [home-assistant/core#103458](https://github.com/home-assistant/core/issues/103458)? This is very annoying blocker ....

Yes, issues are annoying... let's not waste such comments. It doesn't help triaging the issue at hand. Thanks 👍

**Comment by HansRemmerswaal** [comment] 2024-01-08 19:32
> Why this addon cannot encode (eg. base64) query param and decode it again like here -> [home-assistant/core#103458](https://github.com/home-assistant/core/issues/103458)? This is very annoying blocker ....

It's not a blocker, your can roll back to 3.9.2 and continue to run all the queries like in the past.
A few post back is described how to roll back.

**Comment by frenck** [comment] 2024-01-08 21:03
There is no roll back feature in Home Assistant. Restoring a (partial) backup is the only recommended and supported solution.

**Comment by PetrMa** [comment] 2024-01-08 21:15
@frenck maybe this is a good time to revert to HA repository the previous version 3.9.x  until the version 4.x.x will be fixed? There is no benefit with 4.x.x but many problems.

**Comment by HansRemmerswaal** [comment] 2024-01-08 21:16
> There is no roll back feature in Home Assistant. Restoring a (partial) backup is the only recommended and supported solution.

Yes correct a roll back is indeed slightly different than restoring the backup of 3.9.2. 
But what I tried to say is that there is a working solution by using 3.9.2, so users are not blocked.

**Comment by frenck** [comment] 2024-01-08 21:17
> @frenck maybe this is a good time to revert to HA repository the previous version 3.9.x until the version 4.x.x will be fixed? There is no benefit with 4.x.x but many problems.

You can revert yourself if you want to. I rather build a fix than wasting time on other things.

**Comment by pearj** [comment] 2024-01-15 01:14
I found the issue in the upstream project that broke it, they switched SQL queries from POST to GET, which is tripping up the HA ingress security filter:

https://github.com/coleifer/sqlite-web/commit/bae45402470a53e9bf11ec1125f76ea61189b91b

**Comment by pearj** [comment] 2024-01-15 01:40
I created an issue over at https://github.com/coleifer/sqlite-web/issues/140, fingers crossed something can be done.

**Comment by Santanachia** [comment] 2024-01-15 07:43
> I found the issue in the upstream project that broke it, they switched SQL queries from POST to GET, which is tripping up the HA ingress security filter:

it seems that not everyone has GET?
https://github.com/hassio-addons/addon-sqlite-web/issues/281#issuecomment-1825259136

**Comment by pearj** [comment] 2024-01-15 12:50
> it seems that not everyone has GET?

it’s still GET. What they reported is the URL the browser shows, mine is the same. It’s just running in a frame, so you can’t see the query in the URL. But if you right-click view frame source you can see the URL with the GET query.

**Comment by Santanachia** [comment] 2024-01-15 13:35
> it’s still GET. It’s just running in a frame...

you're right, I always opened in a new window, not in a frame and that's why I pointed it out 
https://github.com/hassio-addons/addon-sqlite-web/issues/281#issuecomment-1824316907

**Comment by pearj** [comment] 2024-01-15 21:12
Thanks @coleifer, I really appreciate the quick turnaround even despite not fully agreeing with the underlying reasons.

**Comment by pearj** [comment] 2024-01-20 11:33
If you're willing to "Live on the edge" (pun intended), you can install the Edge version of SQLite Web Addon at: https://addons.community/edge/

It includes the fixed version that was merged in #294. Otherwise, you can wait until the next release whenever that happens.

I just installed the Edge version, which fixes the problem of new lines in SQL queries.

**Comment by baylanger** [comment] 2024-01-30 16:09
> If you're willing to "Live on the edge" (pun intended), you can install the Edge version of SQLite Web Addon at: https://addons.community/edge/
> 
> It includes the fixed version that was merged in #294. Otherwise, you can wait until the next release whenever that happens.
> 
> I just installed the Edge version, which fixes the problem of new lines in SQL queries.
> 
> I'm unsure if the edge version auto-update's though, so it might just a workaround until the next release.
>
I added the edge repository but I'm unclear how to install the add-on from the edge repo. After adding the repo, I uninstalled SQLIteWeb but when trying to install, it still shows v4.1.0. From the HA EDGE page, there's no instructions :(  Would you mind sharing how you've done it?

Thank you.

**Comment by baylanger** [comment] 2024-01-30 21:07
> I was impatient enough
>
Came back here ~5 hours later and read your reply. I was impatient as well, lol. I removed the stable release and now the add-on allows me to install from either stable or edge. Fantastic, thank you!

**Comment by pisolofin** [comment] 2024-02-01 17:32
I tried to install the EDGE version, for me `99c6355`, but i get `404: Not Found` for the query `select * from states`

**Comment by pearj** [comment] 2024-02-02 09:44
Hi @pisolofin,

turns out my SQLite Web auto-upgraded to 99c6355 but it works fine for me with and without spaces in the query.

**Comment by pisolofin** [comment] 2024-02-02 11:35
I tried just now and yes, the query works fine, except for the main page
If I try to run the query from the main page, I get `404: Not Found`
![image](https://github.com/hassio-addons/addon-sqlite-web/assets/5112314/3525a28a-0096-4a9c-8f30-60b94420d6e2)

**Comment by pearj** [comment] 2024-02-04 11:36
Oh you’re right. I hadn't even noticed that query spot on the main page, because I use HA on my phone most of the time. 

I also noticed that if you do a multiline query it does a 400 bad request, so it looks like that still does a GET request there.

**Comment by pearj** [comment] 2024-02-04 11:41
@pisolofin I’ve commented on the SQLite Web issue that's linked to this ticket and will see what happens.

**Comment by coleifer** [comment] 2024-02-04 13:36
Yes my mistake, this is now fixed in 0.6.3 - the index page query form was still using GET and has now been switched to use POST.

**Comment by pearj** [comment] 2024-02-04 21:16
@coleifer that fixes the bad request problem thanks.

@frenck Is it possible for the addon system to pass the base URL prefix through? I think that's why we're getting a 404 because SQLite Web doesn't know its base URL.

**Comment by pearj** [comment] 2024-02-04 21:59
Oh, I can see a previous pull request that tried fixing some URLs in #260. Adding `/query/` to `sqlite-web/rootfs/etc/nginx/templates/ingress.gtpl` will probably fix it, but it is not ideal.

sqlite-web supports providing a base URL with `--url-prefix` I noticed, and it looks like we could provide that here

https://github.com/hassio-addons/addon-sqlite-web/blob/main/sqlite-web/rootfs/etc/s6-overlay/s6-rc.d/sqlite-web/run#L17

Perhaps:

```bash
--url-prefix $(bashio::addon.ingress_entry)
```

I might try it out later.

**Comment by frenck** [comment] 2024-02-04 22:36
Sounds good, feel free to PR that @pearj 👍 

../Frenck

**Closed** 2024-02-09 09:24 UTC

**Comment by HansRemmerswaal** [comment] 2024-02-09 09:32
Closed? I have the latest version but get this error when the query is on 2 lines.

![image](https://github.com/hassio-addons/addon-sqlite-web/assets/116959990/65641a53-44ef-4974-b9b2-b76069007163)

![image](https://github.com/hassio-addons/addon-sqlite-web/assets/116959990/b8dd73a1-f2fd-4e5b-9f81-6187acb7c480)

But from here it works. So maybe the query option on the first page just needs to be removed :)

![image](https://github.com/hassio-addons/addon-sqlite-web/assets/116959990/926f638e-8e66-4919-88f5-473bc974dc79)

**Comment by frenck** [comment] 2024-02-09 09:34
> Closed? I have the latest version but get this error when the query is on 2 lines.

@HansRemmerswaal It has been fixed on dev.

![CleanShot 2024-02-09 at 10 33 09@2x](https://github.com/hassio-addons/addon-sqlite-web/assets/195327/86b3f1f5-b1d2-4b2b-80ec-300cf70fc3da)

Should be part of the next release, currently testing out dev builds on various platforms.

**Comment by HansRemmerswaal** [comment] 2024-02-09 09:55
Sorry, I was to fast :)

Minutes ago the update arrived and I can confirm all is working fine now.

**Comment by frenck** [comment] 2024-02-09 10:06
No worries! Thanks for the confirmation ❤️
